package server.commands;

/**
 * @author Derek Argueta
 */
public enum CommandName {
    GAME_MODEL,
    GAME_LIST_AI,
    GAME_ADD_AI,
    GAMES_LIST,
    GAMES_JOIN,
    GAMES_CREATE,
    MOVES_FINISH_TURN,
    MOVES_SEND_CHAT,
    MOVES_ROLL_NUMBER,
    MOVES_ROB_PLAYER,
    MOVES_BUY_DEV_CARD,
    MOVES_PLAY_YOP,
    MOVES_PLAY_ROAD_BUILDING,
    MOVES_PLAY_MONOPOLY,
    MOVES_PLAY_SOLDIER,
    MOVES_PLAY_MONUMENT,
    MOVES_BUILD_ROAD,
    MOVES_BUILD_SETTLEMENT,
    MOVES_BUILD_CITY,
    MOVES_OFFER_TRADE,
    MOVES_RESPOND_TO_OFFER,
    MOVES_MARITIME_TRADE,
    MOVES_DISCARD_CARDS,
    USER_LOGIN,
    USER_REGISTER
}
